web:
  status:
    templateNotFound:
      code: 4001
      msg: 模板未找到
    formatError:
      code: 4002
    elementNotFound:
      code: 4003
      msg: 元素未找到
    indexOutOfBounds:
      code: 4004
      msg: 数组越界，请检查索引