spring:
  devtools:
    restart:
      enabled: true
  profiles:
    include: swagger,httpStatus
  application:
    name: questionnaire
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    mapper:
      default_view_inclusion: false
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    mongodb:
      uri: mongodb://127.0.0.1/question
  mail:
    default-encoding: UTF-8


  servlet:
    multipart:
      file-size-threshold: 4KB
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
server:
  port: 8000
temp-file:
  dir: /tmp


