TemplateNotFound:
  code: 4001
  msg: 模板未找到
FormatNotCorrect:
  code: 4002
  msg: 格式错误
ElementNotFound:
  code: 4003
  msg: 元素未找到
IndexOutOfBounds:
  code: 4004
  msg: 数组越界，请检查索引
HttpMessageNotReadable:
  code: 4005
  msg: json格式错误，请检查格式
CanNotEdit:
  code: 4006
  msg: 当前状态不能编辑，请切换其编辑状态
UserExists:
  code: 4007
  msg: 当前用户名已存在
Authentication:
  code: 4008
  msg: 认证失败，请检查用户名或密码
Unauthenticated:
  code: 4009
  msg: 认证失败
AuthenticationFailed:
  code: 4009
  msg: 访问被拒绝，请检查权限
ExcelAnalysis:
  code: 4010
  msg: excel导入错误
CanNotCreate:
  code: 5001
  msg: 无法创建文件，请检查当前目录权限
AccessDenied:
  code: 4011
  msg: 当前成员无访问权限，拒绝查看
QuestionnaireNotFound:
  code: 4012
  msg: 未找到当前问卷编号