spring:
  devtools:
    restart:
      enabled: true
  profiles:
    include: swagger,httpStatus
  application:
    name: questionnaire
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    mapper:
      default_view_inclusion: true
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    mongodb:
      uri: mongodb://admin:admin@127.0.0.1/question

server:
  port: 8000


